[general]
fullscreen = true
early-exit = true
corner-roundness = 12
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 0.6
output-filename = "/storage/media/images/screenshot/%Y-%m-%d_%H:%M:%S.png"
save-after-copy = true
default-hide-toolbars = true
primary-highlighter = "block"
disable-notifications = false
actions-on-right-click = []
actions-on-enter = ["save-to-clipboard"]
actions-on-escape = []
right-click-copy = false
no-window-decoration = true
brush-smooth-history-size = 5

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "z"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "g"

[font]
family = "Iosevka Nerd Font Propo"
style = "Bold"

[color-palette]
palette = ["#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#ffd700", "#008000"]

custom = ["#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#ffd700", "#008000"]
